name: image2text
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.0
  google_mlkit_text_recognition: ^0.14.0
  image_picker: ^1.1.2
  permission_handler: ^12.0.0+1
  very_good_analysis: ^7.0.0
  modal_progress_hud_nsn: ^0.5.1
  translator: ^1.0.3+1
  image_cropper: ^9.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  flutter_spinkit: ^5.2.1
  icons_launcher: ^3.0.1




dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
flutter:

  uses-material-design: true

  assets:
    - assets/logo/logo.png

  fonts:
    - family: Avenir
      fonts:
        - asset: assets/fonts/Avenir-Regular.otf


icons_launcher:
  image_path: "assets/logo/logo.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true